name: update share list

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - ".github/workflows/update_share_list.yml"

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Checkout Data
        uses: actions/checkout@v4
        with:
          repository: xiaoyaDev/data
          path: './data'

      -
        name: Update
        run: |
            pikpakshare_list_base64="$(cat ./data/pikpakshare_list.txt | base64)"
            pan115share_list_base64="$(cat ./data/115share_list.txt | base64)"
            quarkshare_list_base64="$(cat ./data/quarkshare_list.txt | base64)"
            awk -v var="${pikpakshare_list_base64}" '
            NR>=1 && NR<=150 && index($0, "pikpakshare_list_base64=") == 1 {
                $0 = "pikpakshare_list_base64=" var
            }
            { print }
            ' all_in_one.sh > tmp && mv tmp all_in_one.sh
            awk -v var="${pan115share_list_base64}" '
            NR>=1 && NR<=150 && index($0, "pan115share_list_base64=") == 1 {
                $0 = "pan115share_list_base64=" var
            }
            { print }
            ' all_in_one.sh > tmp && mv tmp all_in_one.sh
            awk -v var="${quarkshare_list_base64}" '
            NR>=1 && NR<=150 && index($0, "quarkshare_list_base64=") == 1 {
                $0 = "quarkshare_list_base64=" var
            }
            { print }
            ' all_in_one.sh > tmp && mv tmp all_in_one.sh

      - 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: 'chore: update share list'
            branch: master
            file_pattern: 'all_in_one.sh'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
